### ISSUE TITLE
[FEATURE] publish on operatorhub

### ISSUE THREAD

**Issue by ibotty** [openshift/route-monitor-operator#167]
**Is your feature request related to a problem? Please describe.**
I'd like to use the operator on OCP and OKD.

**Describe the solution you'd like**
In the console go to operatorhub and install the route-monitor-operator.

**Comment by georgettica** [comment]
hello @ibotty , glad you are here and asked for this! I will take a look and come back to you :)

**Comment by georgettica** [comment]
I created an internal card for this. I hope we will do it at some point for everyone's advantage :)

**Comment by mJace** [comment]
Hi team, do you have any update on this?
